# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Own Blog | A lifelong learner Blog
email: dcosset@hotmail.fr
description: A blog where I describe some of my personal experiences as I learn to be a better person. # the subpath of your site, e.g. /blog
url: "http://myownblog.github.io" # the base hostname & protocol for your site
twitter_username: DamCosset
github_username:  myownblog
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title
gems: [jekyll-paginate]

#Default Settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Damien Cosset
      layout: "post"
      category: Personal Journal
      comments: true

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
